# Day 6 Task 2: AFL Players

### Stuff to Cover
1. Data Quality Assessment Report
2. Cleaning both csvs
3. Merging
4. Unmatched ID stuff
5. Validation rep
6. Insights

## Imports

In [1]:
import pandas as pd

In [6]:
info_df = pd.read_csv("afl_players_info_raw.csv")
stats_df = pd.read_csv("afl_players_seasonal_stats_raw.csv")

C:\Users\imama\AppData\Local\Temp\ipykernel_17620\621726609.py:2: DtypeWarning: Columns (0: player_id) have mixed types. Specify dtype option on import or set low_memory=False.
  stats_df = pd.read_csv("afl_players_seasonal_stats_raw.csv")

## Data Cleaning

In [7]:
info_df

,id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,height,weight,profile_pic,player_link,player_common_names,player_teams
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,200,100,NaN,https://afltables.com/afl/stats/players/R/Ryan...,NaN,"{Geelong Cats,St Kilda Saints}"
1,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,182,87,NaN,https://afltables.com/afl/stats/players/G/Gary...,NaN,"{Geelong Cats,Gold Coast Suns}"
2,43276,Leek Aleer,Leek_Aleer,Leek,Aleer,2001-08-21,2022-07-30,20,2025-09-06,24,195,85,https://res.cloudinary.com/dijzdikkh/image/upl...,https://afltables.com/afl/stats/players/L/Leek...,NaN,NaN
3,43264,Nathan Ablett,Nathan_Ablett,Nathan,Ablett,1985-12-13,2005-08-12,19,2011-08-28,25,195,95,NaN,https://afltables.com/afl/stats/players/N/Nath...,NaN,"{Geelong Cats,Gold Coast Suns}"
4,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,196,101,NaN,https://afltables.com/afl/stats/players/C/Cain...,NaN,"{Carlton Blues,Port Adelaide Power,St Kilda Sa..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2843,43659,Charlie Curnow,Charlie_Curnow,charlie,CURNOW,1997-02-03,2016-04-03,19,2025-07-24,28,192,96,https://res.cloudinary.com/dijzdikkh/image/upl...,https://afltables.com/afl/stats/players/C/Char...,NaN,{Carlton Blues}
2844,44352,Matt Maguire,Matt_Maguire,matt,MAGUIRE,1984-05-30,2002-05-03,17,2015-04-18,30,192,101,NaN,https://afltables.com/afl/stats/players/M/Matt...,NaN,"{Brisbane Lions,St Kilda Saints}"
2845,45045,Cam Sutcliffe,Cam_Sutcliffe,cam,SUTCLIFFE,1992-05-23,2012-07-08,20,2020-09-05,28,186,87,NaN,https://afltables.com/afl/stats/players/C/Cam_...,NaN,"{Fremantle Dockers,Port Adelaide Power}"
2846,45738,Mark McVeigh,Mark_McVeigh,mark,MCVEIGH,1981-01-26,1999-03-25,18,2012-05-26,31,184,85,NaN,https://afltables.com/afl/stats/players/M/Mark...,NaN,{Essendon Bombers}
2847,44919,Dylan Shiel,Dylan_Shiel,dylan,SHIEL,1993-03-09,2012-03-23,19,2025-08-27,32,182,83,NaN,https://afltables.com/afl/stats/players/D/Dyla...,NaN,NaN

In [4]:
player_info_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2848 entries, 0 to 2847
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2848 non-null   int64
 1   player_name          2848 non-null   str
 2   player_full_name     2848 non-null   str
 3   first_name           2848 non-null   str
 4   last_name            2848 non-null   str
 5   born_date            2848 non-null   str
 6   debut_date           2848 non-null   str
 7   debut_age            2848 non-null   int64
 8   last_date            2848 non-null   str
 9   last_age             2848 non-null   int64
 10  height               2848 non-null   int64
 11  weight               2848 non-null   int64
 12  profile_pic          637 non-null    str
 13  player_link          2848 non-null   str
 14  player_common_names  75 non-null     str
 15  player_teams         2754 non-null   str
dtypes: int64(5), str(11)
memory usage: 356.1 KB

In [5]:
player_info_df.isnull().sum()

id                        0
player_name               0
player_full_name          0
first_name                0
last_name                 0
born_date                 0
debut_date                0
debut_age                 0
last_date                 0
last_age                  0
height                    0
weight                    0
profile_pic            2211
player_link               0
player_common_names    2773
player_teams             94
dtype: int64

In [8]:
stats_df

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25486,ID_43738,2013,Greater Western Sydney Giants,False,1,3.0,1.0,1.0,4.0,0.0,...,2.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,30.0,85.0
25487,ID_43660,2015,Carlton Blues,False,22,216.0,75.0,262.0,478.0,0.0,...,8.4,13.2,0.3,0.0,1.2,0.2,0.2,0.1,79.6,90.5
25488,ID_46153,2025,Melbourne Demons,False,5,15.0,5.0,12.0,27.0,3.0,...,3.4,1.8,0.4,0.8,2.8,0.0,0.4,4.2,30.8,62.4
25489,ID_44965,2005,Fremantle Dockers,False,6,30.0,11.0,41.0,71.0,1.0,...,4.8,7.2,0.0,0.2,1.8,0.2,0.0,1.3,41.5,47.8
25490,ID_45608,1998,carlton blues,False,15,117.0,24.0,97.0,214.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.7,47.4,NaN

In [9]:
stats_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25491 entries, 0 to 25490
Data columns (total 54 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id                    25491 non-null  object
 1   year                         25491 non-null  int64
 2   team                         25491 non-null  str
 3   is_finals                    25491 non-null  bool
 4   games_played                 25491 non-null  int64
 5   kicks                        25439 non-null  float64
 6   marks                        25306 non-null  float64
 7   handballs                    25378 non-null  float64
 8   disposals                    25467 non-null  float64
 9   goals                        22954 non-null  float64
 10  behinds                      22802 non-null  float64
 11  hit_outs                     19785 non-null  float64
 12  tackles                      24980 non-null  float64
 13  rebound_50s                  21958 non-null  float64
 14  inside_50s                   22520 non-null  float64
 15  clearances                   22056 non-null  float64
 16  clangers                     22553 non-null  float64
 17  free_kicks_for               24418 non-null  float64
 18  free_kicks_against           24513 non-null  float64
 19  brownlow_votes               18494 non-null  float64
 20  contested_possessions        22155 non-null  float64
 21  uncontested_possessions      22169 non-null  float64
 22  contested_marks              20566 non-null  float64
 23  marks_inside_50              20326 non-null  float64
 24  one_percenters               21848 non-null  float64
 25  bounces                      19837 non-null  float64
 26  goal_assists                 18399 non-null  float64
 27  total_score                  25491 non-null  int64
 28  total_fantasy_points         25491 non-null  int64
 29  total_percentage_played      19245 non-null  float64
 30  avg_kicks                    25439 non-null  float64
 31  avg_marks                    25306 non-null  float64
 32  avg_handballs                25378 non-null  float64
 33  avg_disposals                25467 non-null  float64
 34  avg_goals                    22954 non-null  float64
 35  avg_behinds                  22802 non-null  float64
 36  avg_hit_outs                 19785 non-null  float64
 37  avg_tackles                  24980 non-null  float64
 38  avg_rebound_50s              21958 non-null  float64
 39  avg_inside_50s               22520 non-null  float64
 40  avg_clearances               22056 non-null  float64
 41  avg_clangers                 22553 non-null  float64
 42  avg_free_kicks_for           24418 non-null  float64
 43  avg_free_kicks_against       24513 non-null  float64
 44  avg_contested_possessions    22155 non-null  float64
 45  avg_uncontested_possessions  22169 non-null  float64
 46  avg_contested_marks          20566 non-null  float64
 47  avg_marks_inside_50          20326 non-null  float64
 48  avg_one_percenters           21848 non-null  float64
 49  avg_bounces                  19837 non-null  float64
 50  avg_goal_assists             18399 non-null  float64
 51  avg_score                    25491 non-null  float64
 52  avg_fantasy_points           25491 non-null  float64
 53  avg_percentage_played        19245 non-null  float64
dtypes: bool(1), float64(47), int64(4), object(1), str(1)
memory usage: 10.3+ MB

In [10]:
stats_df.isnull().sum()

player_id                         0
year                              0
team                              0
is_finals                         0
games_played                      0
kicks                            52
marks                           185
handballs                       113
disposals                        24
goals                          2537
behinds                        2689
hit_outs                       5706
tackles                         511
rebound_50s                    3533
inside_50s                     2971
clearances                     3435
clangers                       2938
free_kicks_for                 1073
free_kicks_against              978
brownlow_votes                 6997
contested_possessions          3336
uncontested_possessions        3322
contested_marks                4925
marks_inside_50                5165
one_percenters                 3643
bounces                        5654
goal_assists                   7092
total_score                       0
total_fantasy_points              0
total_percentage_played        6246
avg_kicks                        52
avg_marks                       185
avg_handballs                   113
avg_disposals                    24
avg_goals                      2537
avg_behinds                    2689
avg_hit_outs                   5706
avg_tackles                     511
avg_rebound_50s                3533
avg_inside_50s                 2971
avg_clearances                 3435
avg_clangers                   2938
avg_free_kicks_for             1073
avg_free_kicks_against          978
avg_contested_possessions      3336
avg_uncontested_possessions    3322
avg_contested_marks            4925
avg_marks_inside_50            5165
avg_one_percenters             3643
avg_bounces                    5654
avg_goal_assists               7092
avg_score                         0
avg_fantasy_points                0
avg_percentage_played          6246
dtype: int64

looks like we got a lotta cleaning to do

### 1. Data Quality Assessment
#### info_df
Gotta check for:
- dupes
- missing vals
- invalid vals (e.g. 0 weight)
- inconsistent logic
- messed up weight/height

In [12]:
# dupe rows
info_df.duplicated().sum()

np.int64(5)

Found 5 dupes

In [13]:
#missing vals
player_info_df.isnull().sum()

id                        0
player_name               0
player_full_name          0
first_name                0
last_name                 0
born_date                 0
debut_date                0
debut_age                 0
last_date                 0
last_age                  0
height                    0
weight                    0
profile_pic            2211
player_link               0
player_common_names    2773
player_teams             94
dtype: int64

In [14]:
#impossible vals
print("rows with weight of 0")
info_df[info_df['weight'] == 0][['id', 'player_name', 'height', 'weight']]

rows with weight of 0

         id      player_name  height  weight
1824  45612  Jack Hutchinson     190       0
2228  46122       Tom Hanily     179       0

Found 2 rows that have weight of 0

In [ ]:
#height and weight
info_df['height'].